### PR TITLE
Allow multiple spinners

### PR DESCRIPTION
**Pull request by neuecc**
Currently Spinner can not run multiple in multi-threading.
broken

This PR stores CursorTop and lock Console operations.

fixed

Also I've found bug of `!CanAcceptEscapeSequence`'s clear line code.

broken_clear

`_lineLength = frame.Length + 1 + Text.Length;` is not work for non-ascii character.
I've modified to ` _lineLength = Console.CursorLeft;` after console out flushed.

### CODE REVIEW

**Comment by neuecc** [comment]
Sorry, after first open PR, I've changed implementation.
to allow other console writing, always render terminator and add `Start(string terminator)` overload.

other1

Also added as a hack, using Console.s_syncObject for lock if can.

**Comment by mayuki** [comment]
Great! But unfortunately, it seems that the output is corrupted when running on CI or `enabled = false` state.

Expected: 
image
Actual (Text will appear in unexpected places):
image

And, in the case of Linux terminal, it will not display correctly at the window buffer boundary.

https://user-images.githubusercontent.com/9012/144692472-570a6d9d-ca49-40d2-b23f-61159b105d59.mp4

The window buffer (`Console.BufferHeight`) other boundary problem seems to exist on Windows as well.
For example, If you run Spinner after `for (var i = 0; i < 10000; i++) { Console.WriteLine(i); }`, an exception is thrown.

image

**Comment by neuecc** [comment]
@mayuki 
thanks, I've fixed both and checked Windows/Linux, CI=1/none enviroments.

If reached window boundary, I've added check of position and subtract new line.

```csharp
_cursorTop = Console.CursorTop;
Console.Write(terminator);
Console.Out.Flush();

// reaches window boundary
if (_cursorTop == Console.CursorTop)
{
    _cursorTop = Math.Max(_cursorTop - 1, 0);
    foreach (var item in s_runningSpinners)
    {
        item._cursorTop = Math.Max(item._cursorTop - 1, 0);
    }
}
```

`-1` doesn't work when the usual Console.WriteLine is sandwiched in between, but it's still better than the previous version (which completely broke the behavior).

**Comment by mayuki** [comment]
> `-1` doesn't work when the usual Console.WriteLine is sandwiched in between, but it's still better than the previous version (which completely broke the behavior).

I would like to consider addressing that case in the future.

**Pull request merged**
